language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

install:
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt
  - npm install -g jslint
  # TODO: Remove when openwisp-users 0.3 is released
  - pip install --upgrade https://github.com/openwisp/openwisp-users/tarball/master/
  # TODO: Remove when latest openwisp-utils is released
  - pip install --upgrade https://github.com/openwisp/openwisp-utils/tarball/master/

before_script:
  - ./run-qa-checks

script:
  - coverage run --source=openwisp_radius runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
