language: python
sudo: false
cache: pip

python:
  - "3.5"

env:
  - DJANGO="django>=2.0,<2.2"

branches:
  only:
    - master

install:
  - # TODO: this is temporary, remove it when django-freeradius 0.1 is released
  - pip install https://github.com/openwisp/django-freeradius/tarball/master
  - # TODO: this is temporary, remove it when openwisp-users > 0.1.10 is released
  - pip install https://github.com/openwisp/openwisp-users/tarball/master
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8
  - ./runisort
  # ensure there are no pending migrations
  - ./tests/manage.py makemigrations openwisp_radius --dry-run | grep "No changes detected"

script:
  - coverage run --source=openwisp_radius runtests.py

after_success:
  coveralls
