language: python
cache: pip
dist: bionic

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

install:
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt
  - npm install -g jslint

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_radius runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls

notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
