[tool.coverage.run]
source = ["openwisp_radius"]
parallel = true
concurrency = ["multiprocessing"]
omit = [
    "openwisp_radius/__init__.py",
    "*/tests/*",
    "*/migrations/*",
]

[tool.docstrfmt]
extend_exclude = ["**/*.py", "README.rst"]

[tool.isort]
known_third_party = ["django"]
known_first_party = ["openwisp_users", "openwisp_utils", "openwisp_radius"]
default_section = "THIRDPARTY"
line_length = 88
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
